export const serverIp = 'https://server.abrahammensah.com'
export const clientIp = 'https://abrahammensah.com'
export const dserverIp = 'http://localhost:4000'
export const dclientIp = 'http://localhost:3000'
export const cryptoKey = '1234'
